name: CI/CD Pipeline

on:
  push:
    branches: main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Check Syntax
        run: npm run lint
      - name: Unit Testing 
        run: npm test
      - name: Build Applicaion 
        run: npm run build

  deploy:
  needs: [test-build]
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to Render
      run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"